ALTER TABLE `wp_tzs_shipments` DROP `cost`;
ALTER TABLE `wp_tzs_shipments` ADD `cost` FLOAT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_shipments` ADD `cash` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_shipments` ADD `nocash` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_shipments` ADD `way_ship` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_shipments` ADD `way_debark` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_shipments` ADD `soft` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_shipments` ADD `way_prepay` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_shipments` ADD `prepayment` FLOAT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_shipments` ADD `price_query` TINYINT NOT NULL DEFAULT 0;

ALTER TABLE `wp_tzs_trucks` DROP `cost`;
ALTER TABLE `wp_tzs_trucks` ADD `cost` FLOAT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_trucks` ADD `cash` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_trucks` ADD `nocash` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_trucks` ADD `way_ship` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_trucks` ADD `way_debark` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_trucks` ADD `soft` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_trucks` ADD `way_prepay` TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_trucks` ADD `prepayment` FLOAT NOT NULL DEFAULT 0;
ALTER TABLE `wp_tzs_trucks` ADD `price_query` TINYINT NOT NULL DEFAULT 0;
